services:
  app:
    build: .
    container_name: excel-reconcile-mvp
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    # Si subes archivos grandes, puedes aumentar el límite de cuerpo en reverse proxy externo.

